# Generated by Django 3.1.7 on 2024-08-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20240823_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='active',
        ),
        migrations.RemoveField(
            model_name='band',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='band',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='band',
            name='official_homepage',
        ),
        migrations.RemoveField(
            model_name='band',
            name='year_formed',
        ),
    ]
