# Generated by Django 3.1.7 on 2024-08-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_band_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
    ]
